using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using DBTeam.Core.Abstractions;
using DBTeam.Core.Models;

namespace DBTeam.Modules.Documenter.Engine;

public sealed class HtmlDocumenter
{
    private readonly IDatabaseMetadataService _meta;
    public HtmlDocumenter(IDatabaseMetadataService meta) { _meta = meta; }

    public async Task<string> BuildAsync(SqlConnectionInfo c, string database, CancellationToken ct = default)
    {
        var sb = new StringBuilder();
        var tables = await _meta.GetTablesAsync(c, database, ct);
        var views = await _meta.GetViewsAsync(c, database, ct);
        var procs = await _meta.GetProceduresAsync(c, database, ct);
        var funcs = await _meta.GetFunctionsAsync(c, database, ct);

        sb.AppendLine("<!doctype html><html><head><meta charset='utf-8'>");
        sb.AppendLine($"<title>Documentation · {Escape(database)}</title>");
        sb.AppendLine("<style>");
        sb.AppendLine(@"
            *{box-sizing:border-box}
            body{font-family:'Segoe UI',system-ui,sans-serif;margin:0;background:#f6f8fa;color:#222}
            header{padding:32px 40px;background:linear-gradient(90deg,#1565c0,#1e88e5);color:#fff}
            header h1{margin:0 0 4px;font-size:28px}
            header p{margin:0;opacity:.85}
            nav{padding:12px 40px;background:#fff;border-bottom:1px solid #e1e4e8;position:sticky;top:0;z-index:10}
            nav a{margin-right:16px;color:#1565c0;text-decoration:none;font-weight:600}
            main{padding:24px 40px;max-width:1200px;margin:0 auto}
            section{background:#fff;border-radius:8px;box-shadow:0 1px 3px rgba(0,0,0,.06);padding:20px;margin-bottom:20px}
            h2{margin:0 0 12px;font-size:20px;color:#1565c0;border-bottom:1px solid #eaeaea;padding-bottom:8px}
            h3{margin:16px 0 6px;font-size:15px;color:#333}
            table{width:100%;border-collapse:collapse;font-size:13px}
            th,td{text-align:left;padding:6px 10px;border-bottom:1px solid #eaeaea}
            th{background:#f1f3f5;font-weight:600;color:#555}
            .pill{display:inline-block;padding:2px 8px;border-radius:10px;background:#e3f2fd;color:#1565c0;font-size:11px;font-weight:600;margin-right:4px}
            .pk{background:#fff3cd;color:#856404}
            .nn{background:#f8d7da;color:#721c24}
            .id{background:#d1ecf1;color:#0c5460}
            .count{color:#777;font-size:13px;margin-left:8px}
        ");
        sb.AppendLine("</style></head><body>");
        sb.AppendLine($"<header><h1>{Escape(database)}</h1><p>Generated by DB TEAM</p></header>");
        sb.AppendLine("<nav><a href='#tables'>Tables</a><a href='#views'>Views</a><a href='#procedures'>Procedures</a><a href='#functions'>Functions</a></nav><main>");

        sb.AppendLine($"<section id='tables'><h2>Tables<span class='count'>{tables.Count}</span></h2>");
        foreach (var t in tables)
        {
            var cols = await _meta.GetColumnsAsync(c, database, t.Schema ?? "dbo", t.Name, ct);
            var fks = await _meta.GetForeignKeysAsync(c, database, t.Schema ?? "dbo", t.Name, ct);
            var idxs = await _meta.GetIndexesAsync(c, database, t.Schema ?? "dbo", t.Name, ct);
            sb.AppendLine($"<h3>{Escape(t.Schema)}.{Escape(t.Name)}</h3>");
            sb.AppendLine("<table><thead><tr><th>Column</th><th>Type</th><th>Nullable</th><th>Flags</th><th>Default</th></tr></thead><tbody>");
            foreach (var col in cols)
            {
                sb.Append($"<tr><td><b>{Escape(col.Name)}</b></td><td>{Escape(col.DataType)}</td><td>{(col.IsNullable ? "Yes" : "No")}</td><td>");
                if (col.IsPrimaryKey) sb.Append("<span class='pill pk'>PK</span>");
                if (col.IsIdentity) sb.Append("<span class='pill id'>IDENTITY</span>");
                if (!col.IsNullable) sb.Append("<span class='pill nn'>NOT NULL</span>");
                sb.AppendLine($"</td><td>{Escape(col.DefaultExpression ?? "")}</td></tr>");
            }
            sb.AppendLine("</tbody></table>");
            if (fks.Count > 0)
            {
                sb.AppendLine("<h3 style='font-size:13px;margin-top:12px'>Foreign keys</h3><ul style='margin:0;font-size:13px'>");
                foreach (var fk in fks)
                    sb.AppendLine($"<li><b>{Escape(fk.Name)}</b>: ({string.Join(",", fk.Columns.Select(x => Escape(x.Column)))}) → {Escape(fk.ReferencedSchema)}.{Escape(fk.ReferencedTable)} ({string.Join(",", fk.Columns.Select(x => Escape(x.ReferencedColumn)))})</li>");
                sb.AppendLine("</ul>");
            }
            if (idxs.Count > 0)
            {
                sb.AppendLine("<h3 style='font-size:13px;margin-top:12px'>Indexes</h3><ul style='margin:0;font-size:13px'>");
                foreach (var i in idxs)
                    sb.AppendLine($"<li><b>{Escape(i.Name)}</b> {(i.IsUnique ? "UNIQUE " : "")}{(i.IsClustered ? "CLUSTERED" : "NONCLUSTERED")} ({string.Join(",", i.Columns.Select(Escape))})</li>");
                sb.AppendLine("</ul>");
            }
        }
        sb.AppendLine("</section>");

        WriteSimpleList(sb, "views", "Views", views);
        WriteSimpleList(sb, "procedures", "Stored procedures", procs);
        WriteSimpleList(sb, "functions", "Functions", funcs);

        sb.AppendLine("</main></body></html>");
        return sb.ToString();
    }

    private static void WriteSimpleList(StringBuilder sb, string id, string title, System.Collections.Generic.IReadOnlyList<DbObjectNode> list)
    {
        sb.AppendLine($"<section id='{id}'><h2>{Escape(title)}<span class='count'>{list.Count}</span></h2>");
        if (list.Count == 0) { sb.AppendLine("<p style='opacity:.6'>None.</p></section>"); return; }
        sb.AppendLine("<ul style='columns:3;margin:0'>");
        foreach (var o in list) sb.AppendLine($"<li>{Escape(o.Schema)}.{Escape(o.Name)}</li>");
        sb.AppendLine("</ul></section>");
    }

    private static string Escape(string? s) => System.Net.WebUtility.HtmlEncode(s ?? "");
}
