title: DB TEAM
description: Professional SQL Server IDE built with WPF
theme: jekyll-theme-cayman
url: "https://khalilbenaz.github.io"
baseurl: "/DBTeam"
show_downloads: true
github:
  is_project_page: true
  repository_url: https://github.com/khalilbenaz/DBTeam
  repository_name: DBTeam
  owner_name: khalilbenaz
  owner_url: https://github.com/khalilbenaz
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - INSTALL.md
  - USER-GUIDE.md
  - ARCHITECTURE.md
  - MODULES.md
  - bmad
